### ISSUE TITLE
Chirp will not build on Bullseye

### ISSUE THREAD

**Issue by km4ack** [km4ack/pi-build#337]
Need to revert to getting chirp from apt until I can figure out how to build from source or build using the flatpak. Currently python-serial and python-gtk2 aren't available on Bullseye. I suspect python-gtk3 may be needed but it isn't currently available either in bullseye.

**Comment by starbasessd** [comment]
Interesting stuff.
http://www.peteronion.org.uk/PyGobjectGtk+3/PyGtk.html
I am also looking at the issue.

**Comment by starbasessd** [comment]
GTK3+ is installed by default in RaspberryPiOS 11 Bullseye. See:
https://downloads.raspberrypi.org/raspios_armhf/release_notes.txt
There are 'work arounds' to get pip2 for python2 installed. I was unable to get flatpak to work due to it being X64, not any version of ARM... 
Writing up a suggestion.

**Comment by starbasessd** [comment]
I can resolve every issue except one, so far, installing chirp in Bullseye on Pi.
sudo apt install libgtk2.0-dev
sudo apt-get install python2 python-dev-is-python2 -y
sudo curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
sudo python2 get-pip.py
sudo pip2 install serial pyserial
sudo apt-get install python-gtk2-dev
at that point, running chirpw, I get an error from Python2 stating unable to load module gtk. 
So far, unable to find any replacements for the python2-gtk module for Bullseye.
Traceback (most recent call last):
  File "./chirpw", line 131, in <module>
    from chirp.ui import mainapp
  File "/home/pi/chirp-daily-20211105/chirp/ui/mainapp.py", line 26, in <module>
    import gtk
ImportError: No module named gtk

**Comment by km4ack** [comment]
will revert to installing with apt until this is resolved.

**Comment by km4ack** [comment]
issue resolved in 3.3.0
